name: Terraform

on:
  
  push:
    branches: ["main"]
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      terraform_action:
        type: choice
        description: 'Select the Terraform action'
        options:
          - Apply
          - Destroy
        required: true

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VPC_ID: ${{ secrets.VPC_ID }}
      SUBNET_ID: ${{ secrets.SUBNET_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "vpc_id=${{ env.VPC_ID }}" -var "subnet_id=${{ env.SUBNET_ID }}"

      - name: Terraform Apply
        if: ${{ github.event.inputs.terraform_action == 'Apply' && github.ref == 'refs/heads/main' }}
        run: terraform apply -var "vpc_id=${{ env.VPC_ID }}" -var "subnet_id=${{ env.SUBNET_ID }}" -auto-approve

      - name: Terraform Destroy
        if: ${{ github.event.inputs.terraform_action  == 'Destroy' }}
        run: terraform destroy -var "vpc_id=${{ env.VPC_ID }}" -var "subnet_id=${{ env.SUBNET_ID }}" -auto-approve
